Small housekeeping

diff --git a/pleasew b/pleasew
--- a/pleasew
+++ b/pleasew
@@ -1,5 +1,5 @@
-#!/bin/bash
-set -eu
+#!/usr/bin/env bash
+set -u
 
 RED="\x1B[31m"
 GREEN="\x1B[32m"
@@ -8,18 +8,21 @@ RESET="\x1B[0m"
 
 DEFAULT_URL_BASE="https://get.please.build"
 # We might already have it downloaded...
-LOCATION=`grep -i "^location" .plzconfig | cut -d '=' -f 2 | tr -d ' '`
+LOCATION=`grep -i "^location" .plzconfig 2>/dev/null | cut -d '=' -f 2 | tr -d ' '`
 if [ -z "$LOCATION" ]; then
     if [ -z "$HOME" ]; then
-	    echo -e "${RED}\$HOME not set, not sure where to look for Please.${RESET}"
+	    echo -e >&2 "${RED}\$HOME not set, not sure where to look for Please.${RESET}"
 	    exit 1
     fi
     LOCATION="${HOME}/.please"
+else
+    # It can contain a literal ~, need to explicitly handle that.
+    LOCATION="${LOCATION/\~/$HOME}"
 fi
 # If this exists at any version, let it handle any update.
 TARGET="${LOCATION}/please"
 if [ -f "$TARGET" ]; then
-    exec "$TARGET" $@
+    exec "$TARGET" ${PLZ_ARGS:-} "$@"
 fi
 
 URL_BASE="`grep -i "^downloadlocation" .plzconfig | cut -d '=' -f 2 | tr -d ' '`"
@@ -28,12 +31,12 @@ if [ -z "$URL_BASE" ]; then
 fi
 URL_BASE="${URL_BASE%/}"
 
-VERSION="`grep -i "^version" .plzconfig`"
+VERSION="`grep -i "^version[^a-z]" .plzconfig`"
 VERSION="${VERSION#*=}"    # Strip until after first =
 VERSION="${VERSION/ /}"    # Remove all spaces
 VERSION="${VERSION#>=}"    # Strip any initial >=
 if [ -z "$VERSION" ]; then
-    echo -e "${YELLOW}Can't determine version, will use latest.${RESET}"
+    echo -e >&2 "${YELLOW}Can't determine version, will use latest.${RESET}"
     VERSION=`curl -fsSL ${URL_BASE}/latest_version`
 fi
 
@@ -45,61 +48,24 @@ if [ "$OS" = "Linux" ]; then
 elif [ "$OS" = "Darwin" ]; then
     GOOS="darwin"
 else
-    echo -e "${RED}Unknown operating system $OS${RESET}"
+    echo -e >&2 "${RED}Unknown operating system $OS${RESET}"
     exit 1
 fi
 # Don't have any builds other than amd64 at the moment.
 ARCH="amd64"
 
-PLEASE_URL="${URL_BASE}/${GOOS}_${ARCH}/${VERSION}/please_${VERSION}.tar.gz"
+PLEASE_URL="${URL_BASE}/${GOOS}_${ARCH}/${VERSION}/please_${VERSION}.tar.xz"
 DIR="${LOCATION}/${VERSION}"
 # Potentially we could reuse this but it's easier not to really.
 if [ ! -d "$DIR" ]; then
     rm -rf "$DIR"
 fi
-echo -e "${GREEN}Downloading Please ${VERSION} to ${DIR}...${RESET}"
+echo -e >&2 "${GREEN}Downloading Please ${VERSION} to ${DIR}...${RESET}"
 mkdir -p "$DIR"
-curl -fsSL "${PLEASE_URL}" | tar -xzpf- --strip-components=1 -C "$DIR"
+curl -fsSL "${PLEASE_URL}" | tar -xJpf- --strip-components=1 -C "$DIR"
 # Link it all back up a dir
 for x in `ls "$DIR"`; do
     ln -sf "${DIR}/${x}" "$LOCATION"
 done
-ln -sf "${DIR}/please" "${LOCATION}/plz"
-
-# Check if they've got any parser engines available.
-if [ -f "/usr/lib/libpypy-c.so" ] || [ -f "/usr/local/lib/libpypy-c.so" ]; then
-    echo -e "${GREEN}Found libpypy for parser engine${RESET}"
-    exec "$TARGET" $@
-fi
-echo -e "${YELLOW}PyPy not found, will check cpython...${RESET}"
-
-# Not worth trying to figure out where libpython might be.
-if ! hash python 2>/dev/null ; then
-    echo -e "${RED}Can't find python, you'll need either Python or PyPy installed for the parser.${RESET}"
-    exit 1
-fi
-
-set +e
-python -c 'import cffi' 2> /dev/null
-if [ $? -eq 0 ]; then
-    echo -e "${GREEN}Found cpython and cffi for parser engine${RESET}"
-    exec "$TARGET" $@
-fi
-
-echo -e "${RED}cffi not installed; you will need to install it: sudo pip install 'cffi>=1.5.0'${RESET}"
-if ! hash pip 2>/dev/null ; then
-    echo -e "${RED}pip doesn't seem to be installed${RESET}"
-    exit 1
-fi
-read -p "${YELLOW}Do you want to install it now? [y/N] ${RESET}" -n 1 -r
-echo -e
-if [[ ! $REPLY =~ ^[Yy]$ ]]; then
-    echo -e "${RED}OK, stopping.${RESET}"
-    exit 1
-fi
-if [ `sudo pip install 'cffi>=1.5.0'` ]; then
-    echo -e "${RED}pip failed${RESET}"
-    exit 1
-fi
-echo -e "${GREEN}Should be good to go now, running plz...${RESET}"
-exec "$TARGET" $@
+echo -e >&2 "${GREEN}Should be good to go now, running plz...${RESET}"
+exec "$TARGET" ${PLZ_ARGS:-} "$@"
